baseURL = "https://tamnd.github.io/blog/"
languageCode = "en-us"
title = "tamnd"
theme = "hugo-bearblog"
enableRobotsTXT = true

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[permalinks]
  blog = "/:slug/"

[params]
  author = "Duc-Tam Nguyen"
  description = "Notes and projects by Duc-Tam Nguyen."
  favicon = "🐻"

[markup]
  [markup.highlight]
    style = "friendly"
    lineNos = true
    lineNumbersInTable = false
    codeFences = true
