baseURL = "https://tamnd.github.io/blog/"
languageCode = "en-us"
title = "tamnd"
theme = "hugo-bearblog"

[params]
  author = "Duc-Tam Nguyen"
  description = "Notes and projects by Duc-Tam Nguyen."
  favicon = "🐻"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/blog/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/blog/about/"
    weight = 2
